keywords:     "ruby, ruby on rails, java, programming, web, c language, android, code, linux"
description:  "This blog is about skills in ruby, ruby on rails, java, programming, web, c language, android, code, linux"

inc:
  # Blog Information
  title:        "Simple, Not Easy"
  subtitle:     "allenlsy.com"
  cover_image:  blog-cover.jpg
  logo:         logo.jpg


  # Company information
  company:      allenlsy
  url:          http://allenlsy.com/
  facebook:     allenlsy
  twitter:      allenlsy
  gplus:        '118230970865161551961'
  # about_link:   /about/

  # Product Information
  # product_link: http://incorporated.sendtoinc.com/
  # tagline:      "Get a modern blog for your company"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname: 'allenlsy'

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true


  # Analytics
  analytics:
    google:
      # eg. 'UA-123-12'
      id: 'UA-24647338-1'

  # Google Fonts
  google_font: 'Open+Sans:400,700,800|Oswald|PT+Mono|Ubuntu+Mono'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

# site author
author:
  name: allenlsy
  twitter: allenlsy
  gplus: 118230970865161551961
  image: avatar.jpg
  logo: logo.jpg
  bio:
      Live in Singapore. Ruby on Rails Developer. Like coffee, music, photography & Chelsea.

# url:         http://incorporated.sendtoinc.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    Asia/Singapore

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: pygments

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []


redcarpet:
  extensions: [ "with_toc_data", "tables", "prettify" ]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  # input: GFM

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

permalink:  /:title

# Links to include in top navigation
# For external links add external: true
links:
  - title: Archives
    url: /archives.html
  - title: About
    url: /about.html
  - title: Tags
    url: /tags.html
  # - title: Casts
  #   url: http://cast.allenlsy.com
  - title: Galleries
    url: /galleries

tag_page_layout: tag_page
tag_page_dir: tags

gallery_theme: fullscreen

gallery_dir: galleries
gallery_layout: gallery

thumbnails_dir: gallery_thumbnails

galleries:
  - name: Sunrise Changi Beach
    excerpt: I went to Changi beach with a group of friends at 5:30am that morning, and wait for the sunrise. We were lucky that day. That is also my first time going out shooting with a group.
    thumbnail: IMG_2635.jpg
  - name: Pulau Ubin, 2014 Febrary
    excerpt: Trip to Pulau Ubin on Chinese New Year
    thumbnail: IMG_2435 - blue.jpg
  - name: Shaanxi Trip
    excerpt: I went back to China on May 1st, for my vacation. Shaanxi is the hometown of my wife. We went together, and saw the mountains and clouds on the highway
    thumbnail: MG_7878.jpg
  - name: Chinatown, 2014 April
    thumbnail: 13810115895_20ab3d2889_o.jpg
  - name: Arab Street, 2014 April
    thumbnail: 13921567052_b2716e13ed_o.jpg
