source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-tagging', github: 'allenlsy/jekyll-tagging'
gem 'jekyll-galleries'
gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
